# =========================
# api-gateway Özel Ayarları
# =========================

server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # Rota tanımlamaları (Eureka ile otomatik bulunabilir veya manuel tanımlanabilir)
      discovery:
        locator:
          enabled: true # Eureka'daki servisleri otomatik olarak rotalara ekle
          lower-case-service-id: true # Servis ID'lerini küçük harfe çevir (örn: /mall-service/**)
      # Örnek Manuel Rota Tanımı (Discovery locator kullanılıyorsa gerekmeyebilir)
      # routes:
      #   - id: mall_route
      #     uri: lb://MALL-SERVICE # Eureka'dan servis adıyla yük dengeleme
      #     predicates:
      #       - Path=/api/v1/malls/**
      #   - id: review_route
      #     uri: lb://REVIEW-SERVICE
      #     predicates:
      #       - Path=/api/v1/reviews/**
      #   # ... diğer servisler için rotalar

# API Gateway'e özel Actuator endpoint'leri
management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway, prometheus, metrics # gateway endpoint'ini ekle

# Loglama
logging:
  level:
    com.avmerkez.apigateway: DEBUG
    org.springframework.cloud.gateway: INFO # Gateway loglarını yönet
