# =========================
# api-gateway Özel Ayarları
# =========================

avmerkez:
  app:
    jwtSecret: "c2VjcmV0IGtleSBtdXN0IGJlIGxvbmcgdGhhbiAyNTYgYml0cw=="
    jwtCookieName: avm_jwt
    jwtRefreshCookieName: avm_refresh_token
    jwtIssuer: avmerkez-user-service
    jwtAudience: avmerkez-api
    jwtExpirationMs: 3600000
    jwtRefreshExpirationMs: 604800000 

server:
  port: ${SERVER_PORT:8080} # API Gateway portu

spring:
  application:
    name: api-gateway
  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      routes:
        - id: user_service_route_login
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/login
        - id: user_service_route_register
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/register
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/api/v1/search/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
        
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics, gateway, configprops, loggers
  endpoint:
    gateway:
      enabled: true

# Loglama
logging:
  level:
    com.avmerkez.apigateway: DEBUG
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO
