# API Gateway specific configurations

server:
  port: 8080 # Gateway port

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      # Route definitions
      routes:
        - id: mall_service_route
          uri: lb://mall-service
          predicates:
            - Path=/api/v1/malls/**
          filters:
            - RewritePath=/api/v1/(?<segment>.*), /${segment}
        - id: store_service_route_by_id
          uri: lb://store-service # store-service'in Eureka ID'si
          predicates:
            - Path=/api/v1/stores/{id} # Mağazaları ID ile getirme/güncelleme/silme
          filters:
            - RewritePath=/api/v1/(?<segment>.*), /${segment}
        - id: store_service_route_list
          uri: lb://store-service
          predicates:
            - Path=/api/v1/stores # Tüm mağazaları veya AVM ID ile filtrelenmişleri listeleme
            - Query=mallId # mallId query parametresi varsa veya yoksa bu route'a girer
          filters:
            - RewritePath=/api/v1/(?<segment>.*), /${segment}
        - id: store_service_route_by_mall # /api/v1/malls/{mallId}/stores gibi
          uri: lb://store-service
          predicates:
            - Path=/api/v1/malls/{mallId}/stores
          filters:
            # Rewrite to /stores?mallId={mallId}
            - RewritePath=/api/v1/malls/(?<mallId>.*)/stores, /stores?mallId=${mallId}


      # Optional: Default filters applied to all routes
      # default-filters:
      #   - name: Retry
      #     args:
      #       retries: 3
      #       statuses: BAD_GATEWAY

# Expose gateway specific actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway, prometheus, metrics 