avmerkez:
  app:
    jwtSecret: "c2VjcmV0IGtleSBtdXN0IGJlIGxvbmcgdGhhbiAyNTYgYml0cw=="
    jwtCookieName: avm_jwt
    jwtRefreshCookieName: avm_refresh_token
    jwtIssuer: avmerkez-user-service
    jwtAudience: avmerkez-api
    jwtExpirationMs: 3600000
    jwtRefreshExpirationMs: 604800000 
# Eureka Client Configuration (Common for most services)
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

# Default Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        # Common endpoints to expose by default
        include: health, info, prometheus, metrics
  # Enable Prometheus metrics endpoint
  endpoint:
    health:
      show-details: when_authorized # or always
    metrics:
      enabled: true
    prometheus:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

# Default Logging Configuration (Example)
logging:
  level:
    root: INFO
    com.avmerkez: DEBUG # Package specific logging level 
