# mall-service specific configurations

# Server Port (0 means random available port)
server:
  port: 0

# Datasource Configuration
spring:
  datasource:
    # Use environment variables or profiles for production secrets
    url: jdbc:postgresql://localhost:5432/mall_db # Example for local dev
    username: user # Example for local dev
    password: password # Example for local dev
    driver-class-name: org.postgresql.Driver
    # Connection pool settings (HikariCP is default)
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update # Use validate or none in production
    show-sql: true # Enable in dev, disable in prod
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Springdoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    # Optional: Group APIs
    # groups:
    #   - name: Malls API
    #     paths-to-match: /malls/**

# Expose service specific actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics, mappings, configprops 