# mall-service specific configurations

# Server Port (0 means random available port)
server:
  port: 8081

# Datasource Configuration
spring:
  datasource:
    url: jdbc:postgresql://postgres_db:5432/mall_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  flyway:
      baseline-on-migrate: true

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update # Use validate or none in production
    show-sql: true # Enable in dev, disable in prod
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Springdoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    # Optional: Group APIs
    # groups:
    #   - name: Malls API
    #     paths-to-match: /malls/**

# Expose service specific actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics, mappings, configprops 
