# =========================
# mall-service Özel Ayarları
# =========================

server:
  port: ${SERVER_PORT:8081} # Ortam değişkeni veya varsayılan port

spring:
  application:
    name: mall-service # Tekrar belirtmekte fayda var
  # Veritabanı Bağlantısı (mall-service'e özel)
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/mall_db
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password} # *** GÜVENLİ YÖNETİLMELİ ***
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  # JPA/Hibernate (mall-service'e özel)
  jpa:
    hibernate:
      ddl-auto: validate # Üretim için 'validate' veya 'none'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # Flyway (mall-service'e özel migration path)
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/mall # VEYA sadece classpath:db/migration

# Servise Özel Loglama
logging:
  level:
    com.avmerkez.mallservice: DEBUG # Geliştirme için DEBUG, üretim için INFO/WARN

# Actuator için farklı yönetim portu (mall-service özelinde tanımlanmış)
management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:9090} # Yönetim portu
