# ==========================
# review-service Özel Ayarları
# ==========================

server:
  port: ${SERVER_PORT:8085}

spring:
  application:
    name: review-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/review_db
    username: ${DB_USER:review_user}
    password: ${DB_PASSWORD:review_password} # *** GÜVENLİ YÖNETİLMELİ ***
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/review # VEYA sadece classpath:db/migration

# Feign Client Ayarları (Örnek: Timeout - gerekirse)
# feign:
#  client:
#    config:
#      mall-service:
#        connectTimeout: 5000
#        readTimeout: 10000
#      store-service:
#        connectTimeout: 5000
#        readTimeout: 10000

# Servise Özel Loglama
logging:
  level:
    com.avmerkez.reviewservice: DEBUG
