# ========================
# store-service Özel Ayarları
# ========================

server:
  port: ${SERVER_PORT:8082} # Store service için varsayılan port

spring:
  application:
    name: store-service
  # Veritabanı Bağlantısı (store-service'e özel)
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/store_db
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  # JPA/Hibernate (store-service'e özel)
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # Flyway (store-service'e özel migration path)
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/store # VEYA sadece classpath:db/migration

# Resilience4j (store-service'e özel Circuit Breaker ayarları)
resilience4j:
  circuitbreaker:
    instances:
      mallServiceClient: # Feign Client bean adı ile eşleşmeli
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        ignoreExceptions:
          - com.avmerkez.storeservice.exception.InvalidInputException
          - feign.FeignException$NotFound

# Servise Özel Loglama
logging:
  level:
    com.avmerkez.storeservice: DEBUG

# Yönetim Portu (store-service özelinde tanımlanmış)
management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:9091} # Yönetim portu
