# ========================
# user-service Özel Ayarları
# ========================

server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/user_db
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        # spring.json.add.type.headers: false # Eğer consumer'ların type header'a ihtiyacı yoksa

avmerkez:
  app:
    kafka:
      topics:
        user-registration: ${KAFKA_TOPIC_USER_REGISTRATION:user-registration-events}
logging:
  level:
    com.avmerkez.userservice: DEBUG
